config/routes.rb
FamilyFeed::Application.routes.draw do

  get "todo/index"

  get "todo/new"

  get "calendar/index"

  get "calendar/new"

  get "calendar/edit"

  get "admin/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :admin
  resources :feed
  resources :comment
  resources :todo
  resources :calendar
  resources :map do
     member do
	get 'show_all'
     end
  end
  
  namespace :admin do
     resources :invite
  end
  
  mount Rapidfire::Engine => "/feedback"

  root :to => 'feed#index'
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :family
  
  has_many :comments
  
  validates_presence_of :date
  validates_presence_of :user
  validates_presence_of :family


#   validates_presence_of :post
  
  def start_time
     date
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
     @events = current_user.family.calendars
     
     pars = params.permit :month, :year
     month = pars[:month].to_i
     year = pars[:year].to_i
     current_user.family.users.map do |u|
	if u.birth && u.birth.month == month
	   @events << Calendar.create(date: Date.new(year, u.birth.month, u.birth.day), family: current_user.family, title: "#{u.name} birthday")
	end
     end
  end

  def new
  end

  def show
    @event = current_user.family.calendars.find_by_id params.require(:id)

    if @event.nil?
      redirect_to :calendar_index
      return
    end
  end

  def edit
     @calendar = Calendar.find_by_id params.require(:id)
  end
  
  def update
     calendar = params.require(:calendar).permit :title, :text, :date
     event_time = DateTime.new calendar['date(1i)'].to_i, calendar['date(2i)'].to_i, calendar['date(3i)'].to_i,
                        calendar['date(4i)'].to_i, calendar['date(5i)'].to_i
     
     @calendar = Calendar.find_by_id params.require(:id)
     @calendar.text = calendar[:text]
     @calendar.title = calendar[:title]
     @calendar.date = event_time
     @calendar.save
     
     current_user.posts.create :text => "<div class='icon-calendar'></div>&nbsp;<small>#{current_user.name} modified <b><a href='/calendar/#{@calendar.id}'>#{calendar[:title]}</a></b> on #{event_time} to the <a href='/calendar'>Calendar</a></small>",
                              :family => current_user.family, :calendar => @calendar
     
     redirect_to calendar_path(@calendar)
  end
  
  def create
    calendar = params.require(:calendar).permit :title, :text, :date
    event_time = DateTime.new calendar['date(1i)'].to_i, calendar['date(2i)'].to_i, calendar['date(3i)'].to_i,
                        calendar['date(4i)'].to_i, calendar['date(5i)'].to_i

    event = current_user.calendars.create :title =>  calendar[:title], :text => calendar[:text], :family => current_user.family,
                                        :date => event_time

    current_user.posts.create :text => "<div class='icon-calendar'></div>&nbsp;<small>#{current_user.name} added <b><a href='/calendar/#{event.id}'>#{calendar[:title]}</a></b> on #{event_time} to the <a href='/calendar'>Calendar</a></small>",
                              :family => current_user.family, :calendar => event
    redirect_to :calendar_index
  end
  
  def destroy
     event = Calendar.destroy params.require(:id)
     
     redirect_to :calendar_index
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendar/_form.html.erb
<div class='left-margin'>
<%= label :calendar, 'Name'  %>
<%= text_field :calendar, 'title' %><br />
<div class='date-time'><%= datetime_select :calendar, 'date' %></div><br />
<%= label :calendar, 'Details' %>
<%= text_area :calendar, 'text', :class => 'text-area-calendar' %>
<br />
<%= submit_tag 'Save', :class => 'btn', :style => 'margin-right: 10px;' %>
<%= link_to 'Cancel', :calendar_index, :class => 'btn btn-danger' %>
</div>

app/views/calendar/_left-menu.html.erb
<div class="span4 left-menu">
  <div class="todo mrm" style="background-color:white"><ul>
    <li class="todo-content">
      <div class="icon-tasks"></div>
      <%= link_to Todo, :todo_index, :class => 'todo-name' %>
    </li>
    <li class="todo-content">
      <div class="icon-calendar"></div>
      <%= link_to Calendar, :calendar_index, :class => 'todo-name' %>
    </li>
    <li class="todo-content">
      <div class="icon-plane"></div>
      <%= link_to 'Map', :map_index, :class => 'todo-name' %>
    </li>
  </ul></div>
</div>

app/views/calendar/_left_menu.html.erb
<div class="span4 left-menu">
  <div class="todo mrm" style="background-color:white"><ul>
    <li class="todo-content">
      <div class="icon-tasks"></div>
      <%= link_to Todo, :todo_index, :class => 'todo-name' %>
    </li>
    <li class="todo-content">
      <div class="icon-calendar"></div>
      <%= link_to Calendar, :calendar_index, :class => 'todo-name' %>
    </li>
    <li class="todo-content">
      <div class="icon-plane"></div>
      <%= link_to 'Map', :map_index, :class => 'todo-name' %>
    </li>
  </ul></div>
</div>

app/views/calendar/edit.html.erb
<%= render :partial => 'feed/menu' %>

<%= form_tag({:action => 'update'}, :method => :put) %>
<%= render 'form' %>

app/views/calendar/index.html.erb
<%= render :partial => 'feed/menu' %>

<div>
  <%= render 'left_menu' %>
<div class='left-margin span12' style="padding-top: 30px">
  <div align='right' style='margin-bottom: -50px;'>
    <%= link_to 'New Event', :calendar_new, :class => 'btn btn-primary' %>
  </div>
<div align='left'>
  <%= calendar @events do |event| %>
      <% if event.title.include? 'birthday' %>
	 <div><%= event.title %></div>
      <% else %>
	 <div><%= link_to event.title, event %></div>
      <% end %>
  <% end %>
</div>
</div>
    </div>

app/views/calendar/new.html.erb
<%= render :partial => 'feed/menu' %>

<div>
  <%= render :partial => 'calendar/left_menu' %>
  <div class='span12'>
    <%= form_tag({:action => 'create'}, :method => :calendar) %>
    <%= render 'form' %>
  </div>
</div>

app/views/calendar/show.html.erb
<%= render :partial => 'feed/menu' %>

<div>
  <%= render :partial => 'calendar/left_menu' %>
  <div class="span12 calendar-show">
      <h1><%= h @event.title %></h1>
      <small>On: <%= h @event.date %> by <%= link_to @event.user.name, show_all_map_path(@event.user.id) %></small>
      <%= link_to "Edit", edit_calendar_path(@event.id), :class => "btn-primary btn-small" %>
      <%= link_to "Delete", calendar_path(@event.id), :class => "btn-small btn-danger task-destroy", 
		  :method => :delete, :data => { :confirm => "Are you sure?" } %>
      <br />
      <br />
      <%= h @event.text %>
      <br /><br />
      <h4>Comments</h4>
      <% if @event.comments != [] %>
	 <div>
	 <% @event.comments.each do |c| %>
	    <div class='comment' id=<%= c.id %>>
	       <b><div class='icon-reply'></div><%= link_to "  " + c.user.name, show_all_map_path(c.user.id) %></b><br />
	       <%= c.text %> <br />
	       <div class="date"><%= c.created_at  %></div>
	    </div>
	 <% end %>
	 </div>
      <% end %>
      <div class="new-comment">
	 <%= render :partial => 'comment/form', :locals => {:event => @event.id} %>
      </div>
  </div>
</div>