config/routes.rb
FamilyFeed::Application.routes.draw do

  get "todo/index"

  get "todo/new"

  get "calendar/index"

  get "calendar/new"

  get "calendar/edit"

  get "admin/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :admin
  resources :feed
  resources :comment
  resources :todo
  resources :calendar
  resources :map do
     member do
	get 'show_all'
     end
  end
  
  namespace :admin do
     resources :invite
  end
  
  mount Rapidfire::Engine => "/feedback"

  root :to => 'feed#index'
end

app/views/admin/_menu.html.erb
<% content_for :menu do %>
<ul class="nav">
<li><a href="/">Home</a></li>
<li><a href="/users/edit">My Account</a></li>
<li class="active"><a href="/admin">Admin</a></li>
<li> <%= link_to "Log Out", :destroy_user_session, :method => :delete %> </li>
</ul>
<% end %>

app/views/admin/index.html.erb
<%= render 'menu' %>

<% unless @family %>
  <div class="hero-unit">
     <h2><%= t('.not_belonging_to_family') %></h2>
     <p><%= t('.ask_for_add') %></p>
     <p>
        <a class="btn btn-primary btn-large" href="/admin/show"><%= t '.create_family' %></a>
     </p>
  </div>
  
<% else %>
   <div class='left-margin'>
     <h2> Family members </h2>
     <div align="right"><%= link_to t('.add_member'), new_admin_path, :class => 'btn btn-primary' %></div><br />
     <table class="table" align="center">
	<tr><td><%= t(:name) %></td><td> Email </td></tr>
        <% @users.each do |user| %>
	    <tr>
	       <td><%= user.name %></td>
	       <td><%= user.email %></td>
	       <td><%= link_to t('.remove_user'), admin_path(user.id), :method => :delete, :data => { :confirm => t(:are_you_sure) } %>
	    </tr>
        <% end %>
     </table>
   </div>
<% end %>

app/views/admin/new.html.erb
<%= render :partial => 'feed/menu' %>

<div class="hero-unit">
   <h2><%= t '.add_an_user' %></h2>
   <p><%= t '.add_or_invite' %></p>
   <p>
      <%= form_tag({:action => 'create'}, :method => :post) %>
      <%= label :email, 'Email' %>
      <%= text_field :users, 'email' %>
   </p><p>
   <%= submit_tag t('.add_user'), :class => 'btn' %></p>
</div>