config/routes.rb
FamilyFeed::Application.routes.draw do

  get "todo/index"

  get "todo/new"

  get "calendar/index"

  get "calendar/new"

  get "calendar/edit"

  get "admin/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :admin
  resources :feed
  resources :comment
  resources :todo
  resources :calendar
  resources :map do
     member do
	get 'show_all'
     end
  end
  
  namespace :admin do
     resources :invite
  end
  
  mount Rapidfire::Engine => "/feedback"

  root :to => 'feed#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :family
  
  has_one :calendar
  has_one :todo
  has_one :checkin
  
  has_many :comments
  
  validates_presence_of :text
  validates_presence_of :user
  
end

app/views/posts/_post.html.erb
<div class="post">
   <b><div class='icon-user'></div><%= link_to "  " + post.user.name, show_all_map_path(post.user.id) %></b><br />
   <%= post.text.html_safe %> <br />
   <div class="date"><% if post.checkin %>
      near <%= link_to post.checkin.gmaps4rails_address, map_path(post.checkin.id) %>,
   <% end %>
   <%= post.created_at  %></div>
   <%= link_to '  Comment', new_comment_path(:post => post.id), :remote => true, :class => 'icon-comment-alt' %> 
   <% if post.comments != [] %>
      
      <div class='comments'>
      <% post.comments.each do |c| %>
	 <div class='comment'>
	    <b><div class='icon-reply'></div><%= link_to "  " + c.user.name, show_all_map_path(c.user.id) %></b><br />
	    <%= c.text %> <br />
	    <div class="date"><%= c.created_at  %></div>
	 </div>
      <% end %>
      </div>
   <% end %>
   <div class="new-comment" id="<%= "new-c#{post.id}" %>"> </div>
</div>