config/routes.rb
FamilyFeed::Application.routes.draw do

  get "todo/index"

  get "todo/new"

  get "calendar/index"

  get "calendar/new"

  get "calendar/edit"

  get "admin/index"

  devise_for :users, :controllers => { :registrations => 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :admin
  resources :feed
  resources :comment
  resources :todo
  resources :calendar
  resources :map do
     member do
	get 'show_all'
     end
  end
  
  namespace :admin do
     resources :invite
  end
  
  mount Rapidfire::Engine => "/feedback"

  root :to => 'feed#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  belongs_to :family
  
#   validates_presence_of :post
  validates_presence_of :user
  validates_presence_of :text
  validates_presence_of :status
  
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  before_filter :authenticate_user!
  
  def index
     @new = Todo.where status: 'new', family_id: current_user.family.id
     @done = Todo.where status: 'done', family_id: current_user.family.id
  end

  def new
  end

  def create
#      post = params[:todo][:text]
     begin
	post = params.require(:todo).require(:text)
     rescue ActionController::ParameterMissing
	redirect_to :todo_index, :alert => 'You should input some text'
	return
     end
	   
     todo = current_user.todos.create :text => post, :family => current_user.family, :status => 'new'
     current_user.posts.create :text => "<div class='icon-tasks'></div>&nbsp;<small>#{current_user.name} added <b>#{post}</b> to the <a href='/todo'>TODO list</a></small>", 
	   :family => current_user.family, :todo => todo
     
     redirect_to :todo_index
  end

  def update
     todo = Todo.find_by_id_and_family_id params.require(:id), current_user.family.id 
     oldstatus = todo.status
     
     if oldstatus == 'new'
	todo.update_attribute :status, 'done'
	current_user.posts.create :text => "<div class='icon-check'></div>&nbsp;<small>#{current_user.name} finished <b>#{todo.text}</b> from the <a href='/todo'>TODO list</a></small>",
	      :family => current_user.family
     elsif oldstatus == 'done'
	todo.update_attribute :status, 'new'
	current_user.posts.create :text => "<div class='icon-check-empty'></div>&nbsp;<small>#{current_user.name} reopened <b>#{todo.text}</b> on the <a href='/todo'>TODO list</a></small>",
	      :family => current_user.family
     end
     
     redirect_to :todo_index
  end
  
  def destroy
     Todo.find_by_id_and_family_id(params.require(:id), current_user.family.id).destroy
     
     redirect_to :todo_index
  end
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/todo/_form.html.erb
<%= form_tag({:action => 'create'}, :method => :post) %>
<%= text_field :todo, 'text', :maxlength => 110, :class => 'new-task-label' %>
<%= submit_tag 'Add to the list', :class => 'btn btn-primary', :style => 'margin-top:-12px;' %>

app/views/todo/index.html.erb
<%= render :partial => 'feed/menu' %>

<div>
  <%= render :partial => 'calendar/left_menu' %>
  <div class='span12'>
<div class="add-task">
   <%= render 'form' %>
</div>

<div class="tasks">
   <ul class="new-tasks unstyled">
      <% @new.each do |task| %>
	 <li class="task">
	    <div class="row-fluid">
	       <div class="task-checkbox">
		  <%= link_to (check_box_tag "new", task.id, false, :class => 'task-checkbox'), todo_path(task.id), :method => :put %>
	       </div>
	       <div class="task-text" >
		  <%= task.text %>
		  <%= link_to "Delete", todo_path(task.id), :class => "btn-small btn-danger task-destroy", 
		     :method => :delete, :data => { :confirm => t(:are_you_sure) } %>
	       </div>
	    </div>
	    </li>
      <% end %>
   </ul>
</div>

<h3 style="margin-left:10px;"><%= t :done %></h3>
<div class="tasks">
   <ul class="new-tasks unstyled">
      <% @done.each do |task| %>
	 <li class="task">
	    <div class="row-fluid">
	       <div class="task-checkbox">
		  <%= link_to (check_box_tag "new", task.id, true, :class => 'task-checkbox'), todo_path(task.id), :method => :put %>
	       </div>
	       <div class="task-text" >
		  <%= task.text %>
		  <%= link_to "Delete", todo_path(task.id), :class => "btn-small btn-danger task-destroy", 
		     :method => :delete, :data => { :confirm => t(:are_you_sure) } %>
	       </div>
	    </div>
	    </li>
      <% end %>
   </ul>
</div>
   </div></div>

app/views/todo/new.html.erb
<h1>Todo#new</h1>
<p>Find me in app/views/todo/new.html.erb</p>